doc(README): add Shubham as a contributor
shoonyatech/wallora.com pull request #160
Opened 2021-09-06 17:19 UTC by SHUBHAMDAVE001

Fixes #<issue no>
Screenshot: (if applicable):  
Description of the change:

2021-09-07 03:00 UTC, souvikbasu requested changes
set commit message in the format specified as-
doc(README): add Shubham as a contributor

2021-09-07 03:00 UTC, souvikbasu commented on README.md
> +- Shubham Dave (@SHUBHAMDAVE001)
set GitHub username in small letters

2021-09-07 16:19 UTC, SHUBHAMDAVE001 commented on README.md
> +- Shubham Dave (@SHUBHAMDAVE001)
Okay sure.

2021-09-09 17:55 UTC, souvikbasu requested changes
please fix commit message as discussed before

2021-09-09 17:56 UTC, closed without merging