feat(home): add Wallora logo to header
shoonyatech/wallora.com pull request #66
Opened 2021-05-16 11:22 UTC by priyankajayaswal

Fixes: #54 

Logged in case: 
![image](https://user-images.githubusercontent.com/36433785/118395208-ad93dc00-b666-11eb-9faf-7f1cfbd768e2.png)

Logged out case: 
![image](https://user-images.githubusercontent.com/36433785/118395154-73c2d580-b666-11eb-8706-d40d76a02ed1.png)

2021-05-17 07:12 UTC, souvikbasu requested changes
since Aryaman was assigned to the issue, let's allow him to send the PR if he can

2021-05-17 07:12 UTC, souvikbasu commented on components/Footer.tsx
> +        <div className="bg-violet-200 p-5 mt-2 flex justify-between">
should be using theme variable instead like `primary-color`

2021-05-17 07:12 UTC, souvikbasu commented on components/Header.tsx
> +            <img src="./images/wallora-logo-170x53.jpeg"></img>
add alt text for image

2021-05-17 07:12 UTC, souvikbasu commented on components/Header.tsx
> +                props.user ? <a href="/api/auth/logout" className={className}>Logout</a> : <a href="/api/auth/login" className={className}>Login</a>
use tailwind classes instead of className

2021-05-17 07:12 UTC, souvikbasu commented on pages/_app.tsx
> +import "./styles/app.css"
do not use custom CSS if can be done using tailwind

2021-05-17 07:12 UTC, souvikbasu commented on pages/styles/app.css
> +.prominent-button {
integrate material UI lib

2021-05-17 07:12 UTC, souvikbasu commented on tailwind.config.js
> +        200: "#f4dcf4"
set theme variable name as `primary-color`

2021-05-17 07:12 UTC, souvikbasu commented on tailwind.config.js
> +        200: "#f4dcf4"
so that tomorrow we can decide to use another color without having to change its usage at all places

2021-05-17 16:00 UTC, aryamantodkar commented
> since Aryaman was assigned to the issue, let's allow him to send the PR if he can

I have assigned myself to the terms and privacy issue

2021-05-24 01:19 UTC, souvikbasu approved these changes

2021-05-24 05:09 UTC, merged