feat(style): add theming support
shoonyatech/wallora.com pull request #70
Opened 2021-05-18 19:43 UTC by vctc

Fixes: #17 

![image](https://user-images.githubusercontent.com/4219835/118713266-5a28b600-b83f-11eb-907f-ed24ac72c11e.png)

2021-05-18 20:01 UTC, souvikbasu requested changes
Do we need styles/main.css as it contains explicit CSS statements. Is there anything we are not able to achieve using Tailwind for theming?

2021-05-18 20:01 UTC, souvikbasu commented on tailwind.config.js
> +      backgroundImage: (theme) => ({
can we format all files in the project as a commit so that we don't see formatting differences again for any other PR. This change is ok for now

2021-05-18 20:11 UTC, vctc commented on styles/global.css
> +@tailwind base;
Already we used inbuilt tailwind.css. Since we are customizing our theme we need this file to build the customized css

2021-05-19 04:38 UTC, vctc commented
> Do we need styles/main.css as it contains explicit CSS statements. Is there anything we are not able to achieve using Tailwind for theming?

removed main.css and tested the app. its working perfect. But we need global.css.

2021-05-19 06:01 UTC, souvikbasu approved these changes

2021-05-19 06:01 UTC, merged