feat(template) : create default template for pr
shoonyatech/wallora.com pull request #81
Opened 2021-05-21 14:57 UTC by hussamkhatib

This PR fixes issue #9

2021-05-21 17:54 UTC, souvikbasu requested changes

2021-05-21 17:54 UTC, souvikbasu commented on .github/pull_request_template.md
> +Description of the change:
Also, add a line for "Screenshot (if applicable):"

2021-05-21 17:54 UTC, souvikbasu commented on .github/pull_request_template.md
> +Description of the change:
Add Screenshot before Description

2021-05-22 13:25 UTC, hussamkhatib commented
![Screenshot from 2021-05-22 18-54-02](https://user-images.githubusercontent.com/52914487/119228145-3f9c5880-bb2f-11eb-80cf-d983a50cedc1.png)

2021-05-25 16:24 UTC, souvikbasu requested changes

2021-05-25 16:24 UTC, souvikbasu commented on .github/pull_request_template.md
> +Screenshot (if applicable)
need a colon at the end like in Description:

2021-05-26 05:49 UTC, souvikbasu approved these changes

2021-05-26 05:49 UTC, merged