Footer
shoonyatech/wallora.com pull request #94
Opened 2021-05-29 08:28 UTC by hussamkhatib

Screenshot: (if applicable):   looks the same , no changes
Description of the change: change the tag for footer from header to footer.
Add Link wrapper for the anchor tags

2021-05-29 08:59 UTC, hussamkhatib commented
Update : It looks the same ,except that it doesn’t have the box shadow which came from material ui. Also i dint add the position:sticky to it, which was also provided with material ui prop earlier.

2021-05-30 19:27 UTC, souvikbasu requested changes

2021-05-30 19:27 UTC, souvikbasu commented on .github/pull_request_template.md
> +This PR Fixes : #__
please rebase. This change is already merged

2021-05-30 19:27 UTC, souvikbasu commented on components/Footer/index.tsx
> +    <footer className="bg-primary">
should use AppBar instead as we are using material UI for footer

2021-05-31 20:12 UTC, souvikbasu approved these changes

2021-05-31 20:13 UTC, merged